export const GETCATEGORY = "GETCATEGORY";
export const CHANGEOUTPUT = "CHANGEOUTPUT";
export const SETPARAMS = "SETPARAMS";
export const LOADFILTERS = "LOADFILTERS";
export const UPDATECURRENTCATEGORY = "UPDATECURRENTCATEGORY";
export const TRYOPENFILTER = "TRYOPENFILTER";